### ISSUE TITLE
Simple way to move expand toggle to left of property

### ISSUE THREAD

**Issue by redonkulus** [lmenezes/json-tree#9]
@lmenezes nice, simple library for tree view. 

I was wondering if you could advise what modifications would be required to move the object property expand to the left of the property name. For example, now its:
```
"foo": { -
```
I'd like to change it to:
```
- "foo": {
```
I think it would make the toggle a little easier to find and use, similar to how Devtools and others do. I don't think this library needs to change, I would modify in my own fork. 

I've tried swapping [`_collapseElem()`](https://github.com/lmenezes/json-tree/blob/master/jsontree.js#L88) to be above `opening` in `_collection()`. However, I'm not sure what changes are needed for the [`_property()`](https://github.com/lmenezes/json-tree/blob/master/jsontree.js#L122) method. Seems that the `_hide()` method requires changes too. 

I know this is an odd request but any guidance is apprecited.

**Comment by lmenezes** [comment]
@redonkulus Hi!

Right now I think this won't be really straightforward to do, but I like the idea of moving this to the left side. I will try to find sometime during the weekend to work on it, although if you want to give it a shot yourself, that would also be welcome :)

**Comment by redonkulus** [comment]
Thanks for replying. I've been trying to change it myself, but I keep getting tripped up on the object parsing. I can't figure out how to include the property name and : after the collapse element. It might simpler for you since you have more context. 

One other thing I did enhance was to use arrows in place of the + and - toggles. I basically just tried to match what Chrome does.

**Comment by lmenezes** [comment]
@redonkulus I think this should work now. I haven't really found the time to document and explain it well, but looking at the latest .css you can figure out how to change the symbols(+/-) and the collapsing is now displayed on the left hand side as opposed to *after* the opening bracket. hope that works for you.

**Comment by redonkulus** [comment]
Just tried this, it works great! Love the improvements to the DOM to use semantic markup and remove all the `&nbsp;`. Good work! Thanks for the quick turn around.

**Comment by lmenezes** [comment]
Glad to hear :)

I have this pretty much abandoned, as I never felt it was really in a state to be used by others. So, having someone else finding it useful provides some motivation for cleaning up (even if just a little).

**Comment by redonkulus** [comment]
Ya I checked out a bunch of other ones, but there was so much code and they were a bloated mess. Yours had the cleanest, readable code that I could easily tweak. 

I actually pulled yours down and converted it to TypeScript for an internal project of mine. It's been working great thus far. 

Also, you can call it "stable", not "abandoned". 😀
